/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

/**
 *
 * @author Estuardo Ramos
 */
import com.mycompany.practica1_estructura_de_datos.main.Apuesta;
import com.mycompany.practica1_estructura_de_datos.main.Pasos;

public class SelecionarGanadores extends javax.swing.JFrame {

    Apuesta apuestas[];
    int pasosVerifica;
    int pasosResult;
    Pasos pasos;

    /**
     * Creates new form SelecionarGanadores
     */
    public SelecionarGanadores() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        caballo1Puesto = new javax.swing.JTextField();
        caballo2Puesto = new javax.swing.JTextField();
        caballo3Puesto = new javax.swing.JTextField();
        caballo4Puesto = new javax.swing.JTextField();
        caballo5Puesto = new javax.swing.JTextField();
        caballo6Puesto = new javax.swing.JTextField();
        caballo7Puesto = new javax.swing.JTextField();
        caballo8Puesto = new javax.swing.JTextField();
        caballo9Puesto = new javax.swing.JTextField();
        caballo10Puesto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Caballo 1");

        jLabel2.setText("Caballo 2");

        jLabel3.setText("Caballo 3");

        jLabel4.setText("Caballo 4");

        jLabel5.setText("Caballo 5");

        jLabel6.setText("Caballo 6");

        jLabel7.setText("Caballo 7");

        jLabel8.setText("Caballo 8");

        jLabel9.setText("Caballo 9");

        jLabel10.setText("Caballo 10");

        caballo3Puesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caballo3PuestoActionPerformed(evt);
            }
        });

        caballo4Puesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caballo4PuestoActionPerformed(evt);
            }
        });

        caballo5Puesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caballo5PuestoActionPerformed(evt);
            }
        });

        caballo9Puesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caballo9PuestoActionPerformed(evt);
            }
        });

        caballo10Puesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caballo10PuestoActionPerformed(evt);
            }
        });

        jLabel11.setText("Ingrese los puestos ");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caballo1Puesto)
                            .addComponent(caballo2Puesto)
                            .addComponent(caballo3Puesto)
                            .addComponent(caballo4Puesto)
                            .addComponent(caballo5Puesto)
                            .addComponent(caballo6Puesto)
                            .addComponent(caballo7Puesto)
                            .addComponent(caballo8Puesto)
                            .addComponent(caballo9Puesto)
                            .addComponent(caballo10Puesto)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel11)
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(caballo1Puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caballo2Puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caballo3Puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(caballo4Puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(caballo5Puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(caballo6Puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(caballo7Puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(caballo8Puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(caballo9Puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(caballo10Puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(42, 42, 42))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caballo3PuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caballo3PuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caballo3PuestoActionPerformed

    private void caballo4PuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caballo4PuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caballo4PuestoActionPerformed

    private void caballo5PuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caballo5PuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caballo5PuestoActionPerformed

    private void caballo9PuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caballo9PuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caballo9PuestoActionPerformed

    private void caballo10PuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caballo10PuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caballo10PuestoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ingresoResultados();
    }//GEN-LAST:event_jButton1ActionPerformed

   

    public void recibir(Apuesta[] ap, Pasos pasos) {
        apuestas = ap;
        this.pasos=pasos;
        
    }

    public void ingresoResultados() {
        int[] result = new int[10];
        result[0] = Integer.valueOf(caballo1Puesto.getText());
        result[1] = Integer.valueOf(caballo2Puesto.getText());
        result[2] = Integer.valueOf(caballo3Puesto.getText());
        result[3] = Integer.valueOf(caballo4Puesto.getText());
        result[4] = Integer.valueOf(caballo5Puesto.getText());
        result[5] = Integer.valueOf(caballo6Puesto.getText());
        result[6] = Integer.valueOf(caballo7Puesto.getText());
        result[7] = Integer.valueOf(caballo8Puesto.getText());
        result[8] = Integer.valueOf(caballo9Puesto.getText());
        result[9] = Integer.valueOf(caballo10Puesto.getText());
        calcularResultados(apuestas, result);
    }

    public void calcularResultados(Apuesta[] apuestasGanadores, int[] resultado) {
        int puestoApuesta[];
        for (int j = 0; j < apuestasGanadores.length; j++) {
            pasosResult++;
            puestoApuesta = apuestasGanadores[j].getPuestos();
            System.out.println("name "+apuestasGanadores[j].getNombre()+apuestasGanadores[j].isValido());
            if (apuestasGanadores[j].isValido()) {
                for (int i = 0; i < 10; i++) {
                    pasosResult++;
                    if (puestoApuesta[i] == resultado[i]) {
                        System.out.println("apuesta de " + apuestasGanadores[j].getNombre() + " " + puestoApuesta[i] + "es igual a " + resultado[i] + " num " + i);
                        apuestasGanadores[j].sumarPuntos(resultado[i]);
                    }
                    //System.out.println("apuesta de "+apuestasGanadores[j].getNombre()+" "+puestoApuesta[i]);
                }

            }

            //System.out.println("posiciones " + resultado[j]);
            System.out.println("puntos de " + apuestasGanadores[j].getNombre() + " " + apuestasGanadores[j].getPuntos());
        }
        //cambiar pestaña
        pasos.setPasosResultado(pasosResult);
        Resultados resultados = new Resultados();
        resultados.recibirApuestas(apuestas, resultado, pasos);
        setVisible(false);
        resultados.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField caballo10Puesto;
    private javax.swing.JTextField caballo1Puesto;
    private javax.swing.JTextField caballo2Puesto;
    private javax.swing.JTextField caballo3Puesto;
    private javax.swing.JTextField caballo4Puesto;
    private javax.swing.JTextField caballo5Puesto;
    private javax.swing.JTextField caballo6Puesto;
    private javax.swing.JTextField caballo7Puesto;
    private javax.swing.JTextField caballo8Puesto;
    private javax.swing.JTextField caballo9Puesto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
